### ISSUE TITLE
Failed to launch the API

### ISSUE THREAD

**Issue by Parkerlee0619** [kfsoftware/meetup-k8s-hlf-2023#3]
I successfully built the Fabric network, created the channel and installed the chaincode, but I got an error when I launch the Client API. My K8s cluster got all the nodes and pods mentioned at the end of the tutorial running, but when I tried to start the API, it got these errors:

error: [FabricCAClientService.js]: Failed to enroll enroll, error:%o message=Calling enroll endpoint failed with error [Error: connect ECONNREFUSED ::1:443], stack=Error: Calling enroll endpoint failed with error [Error: connect ECONNREFUSED ::1:443]
    at ClientRequest.<anonymous> (/fabric/tutorial/meetup-k8s-hlf-2023/client/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:19)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21), errno=-111, code=ECONNREFUSED, syscall=connect, address=::1, port=443
Error: Calling enroll endpoint failed with error [Error: connect ECONNREFUSED ::1:443]
    at ClientRequest.<anonymous> (/fabric/tutorial/meetup-k8s-hlf-2023/client/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:19)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[ERROR] 12:02:25 Error: Calling enroll endpoint failed with error [Error: connect ECONNREFUSED ::1:443]

**Comment by Giorgiovisco** [comment]
Hi i am getting the same issue, did you manage to resolve it?
